### ISSUE TITLE
proposal: let readtags supports pipe operation

### ISSUE THREAD

**Issue by leleliu008** [universal-ctags/libreadtags#32]
the `roundtrip` test is very cost time. following is my test on Cygwin:
```
time make roundtrip ROUNDTRIP_MAX_ENTRIES=25
  RUN      roundtrip

real    26m22.943s
user    6m31.521s
sys     17m17.589s
```

From the above information, we can known that the most time consuming is in kernel mode, I guess the fread(3) functoin cause. so we can use stdin to avoid frequently invoke fread(3)

**Comment by k-takata** [comment]
In general, creating a process using fork() on Cygwin is very slow.
E.g.

On Cygwin:
```
$ while true; do date; done | uniq -c
     62 Wed May 19 13:15:43 JST 2021
     71 Wed May 19 13:15:44 JST 2021
     72 Wed May 19 13:15:45 JST 2021
```

On WSL2 on the same Windows machine:
```
$ while true; do date; done | uniq -c
   1818 Wed May 19 13:06:57 JST 2021
   2032 Wed May 19 13:06:58 JST 2021
   1944 Wed May 19 13:06:59 JST 2021
```

Cygwin is about 30x slower.

The roundtrip test forks `readtags` for every tags file, right?

**Comment by leleliu008** [comment]
@k-takata a good point of view. can we support `./readtags -t Units/parser-cmake.r/cmake-macro.d/expected.tags - a && b && c ...`

**Comment by masatake** [comment]
As @k-takata did for units.py, writing roundtrip.py may reduce fork calls.

**Comment by leleliu008** [comment]
`while true; do date; done | uniq -c` IO operation is involved in this example, so I think can't confirm the reason is fork(). 
we should write a C example to confirm.

**Comment by leleliu008** [comment]
run following can confirm
```
//#include <stdio.h>
#include <unistd.h>

int main() {
        fork();
        fork();
        fork();

        fork();
        fork();
        fork();

        fork();
        fork();
        fork();

        fork();
        fork();
        fork();

        fork();
        fork();

        int i = 0;
        i++;

        //printf("hello\n");

        return 0;
}
```
this will fork **2 ** 14 = 16384** child process. there are **15980** tags in Units dir.

**Comment by k-takata** [comment]
This is a simple well-known way to measure the speed of fork().
Here are some related pages:
https://superuser.com/questions/133313/can-i-speed-up-cygwins-fork
https://stackoverflow.com/questions/11032161/why-is-cygwin-so-slow
The second page has a bench mark written in C.

**Comment by masatake** [comment]
> The roundtrip test forks readtags for every tags file, right?

No. The roundtrip test forks readtags for every tag entry for every tags file.
Using pipe for receiving a search word may improve the situation because it reduces forks.

 readtags command is a part of ctags.
I have to transfer this issue back to ctags repo.

**Comment by masatake** [comment]
I found we can split the command into two parts like:

```
$ readtags --server /path/to/unix-socket tags_file &
$ readtags --client /path/to/unix-socket ... pattern0
$ readtags --client /path/to/unix-socket ... pattern1
$ readtags --client /path/to/unix-socket ... pattern2
...
$ readtags --server-quit /path/to/unix-socket
```

Though we cannot reduce the number of fork calls, we can reduce the number of read and seek calls if ctags reads the contents of the tags file at start up time.

We can extend this pattern more:
```
$ ctags --server /path/to/unix-socket
$ ctags --client /path/to/unix-socket input.c
$ ctags --client /path/to/unix-socket -R srcdir
$ readtags --client  /path/to/unix-socket ... pattern2
```

No tags file appears in this story.
As you may notice, people may call this LSP:-)

**Comment by masatake** [comment]
I wrote a glue code for using mmap for reading tags file. See #33.

**Comment by masatake** [comment]
I introduced minitrip, the way to run a subset of roundtrip in CI environments.
https://github.com/universal-ctags/ctags/pull/3066

**Comment by masatake** [comment]
I implemented the way to read tags data from stdin in the readtags command side.
 
```
    -t TAGFILE | --tag-file TAGFILE
        Use specified tag file (default: "tags").
        "-" indicates taking tag file data from standard input.
```

Internally, the command copies the input from stdin to a temporary file.
After copying, the command processes the temporary file. So `-t -` doesn't improve the performance in any aspect.
It can simplify the command line when combining readtags with `ctags -o -`.
