### ISSUE TITLE
the limitation of ftell/fseek

### ISSUE THREAD

**Issue by masatake** [universal-ctags/libreadtags#36]
On mingw64, we observed that ftell returned -1 but it set errno 0.
After inspecting we found it happened when giving a tags file larger than 2GB.

- [x] introduce new enumerator to tagErrno enumeration,
- [x] use _ftelli64 and _fseeki64 on that platform, and
- [x] write test cases.

----

I found the reason.
In libreadtags, a library used in the readtags command, ftell() is used to get the current file position in tags file.
ftell() returns `long` value. However, "long" is too small for the original.tags. original.tags is larger than 2GB.
https://stackoverflow.com/questions/4003405/32-bit-windows-and-the-2gb-file-size-limit-c-with-fseek-and-ftell

It will take time for fixing this.
Making the tags file smaller can be a workaround.

When running ctags, pass "--kinds-C=-zl" and "--kinds-C++=-zl" to the command line like:
```
ctags
-o
%TAGSFILE%
;; programming languages to be scanned
--languages=C,C++
--kinds-all=*
--kinds-C=-zl
--kinds-C++=-zl
--fields=*
--extras=*
-R
```

`z` means function parameters.
`l` means function local variables.
Not tagging these kinds may reduce the size of tags file.

_Originally posted by @masatake in https://github.com/universal-ctags/ctags/issues/3370#issuecomment-1113862598_

**Comment by lambertlulala** [comment]
Hi @masatake , I have created a PR https://github.com/universal-ctags/libreadtags/pull/37 for this issue, and it works fine on my platform. It's built from mingw64.

**Comment by masatake** [comment]
As the preparation for merging #37, I introduced an error constant representing "too large tags file" in #39. The error must be reported till #37 is merged. When we merge #37, the error should not be reported on the platform.
